parameters:
     locale: 'en'
      # This parameter defines the codes of the locales (languages) enabled in the application
     app_locales: en|ru
     app.notifications.email_sender: hodacodakovskiy@gmail.com

services:
    _defaults:
        autowire: true
        autoconfigure: true
